// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarMenuController from "./avatar_menu_controller"
application.register("avatar-menu", AvatarMenuController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DynamicSelectController from "./dynamic_select_controller"
application.register("dynamic-select", DynamicSelectController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import RightController from "./right_controller"
application.register("right", RightController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidebarMenuController from "./sidebar_menu_controller"
application.register("sidebar-menu", SidebarMenuController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
