services:
  db:
    image: mysql:5.7
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    #   - ./tmp/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn install && bin/dev"
    volumes:
      - .:/myapp
      - ./tmp/docker/node_modules:/myapp/node_modules
    tty: true
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_SOCKET: ''
      GMAIL_USERNAME: 's'
      GMAIL_PASSWORD: 's'
      DELIVERY_METHOD: test
      # CODECOV_TOKEN: ${CODECOV_TOKEN}
    depends_on:
      - db
  mailer:
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/sidekiq"
    volumes:
      - .:/myapp
