services:
  db:
    image: mysql:5.7
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    #   - ./tmp/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn install && bin/dev"
    volumes:
      - .:/myapp
      - ./tmp/docker/node_modules:/myapp/node_modules
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      DB_SOCKET: ''
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      GMAIL_USERNAME: 's'
      GMAIL_PASSWORD: 's'
      DELIVERY_METHOD: smtp
      SMTP_SERVER: mailer
      SMTP_PORT: 1025
      REDIS_URL: redis://redis:6379
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      SELENIUM_APP_HOST: web
      TEST_PORT: 3001
    depends_on:
      - db
      - redis
  mailer:
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:7.0.9-alpine3.17
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
    volumes:
      - .:/myapp
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_SOCKET: ''
      GMAIL_USERNAME: 's'
      GMAIL_PASSWORD: 's'
      DELIVERY_METHOD: smtp
      SMTP_SERVER: mailer
      SMTP_PORT: 1025
      REDIS_URL: redis://redis:6379


  selenium:
    image: seleniarm/standalone-chromium:111.0-chromedriver-111.0-grid-4.8.3-20230402 # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
