require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/emergency_contacts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EmergencyContact. As you add validations to EmergencyContact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmergencyContact.create! valid_attributes
      get emergency_contacts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      emergency_contact = EmergencyContact.create! valid_attributes
      get emergency_contact_url(emergency_contact)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_emergency_contact_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      emergency_contact = EmergencyContact.create! valid_attributes
      get edit_emergency_contact_url(emergency_contact)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmergencyContact" do
        expect {
          post emergency_contacts_url, params: { emergency_contact: valid_attributes }
        }.to change(EmergencyContact, :count).by(1)
      end

      it "redirects to the created emergency_contact" do
        post emergency_contacts_url, params: { emergency_contact: valid_attributes }
        expect(response).to redirect_to(emergency_contact_url(EmergencyContact.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmergencyContact" do
        expect {
          post emergency_contacts_url, params: { emergency_contact: invalid_attributes }
        }.to change(EmergencyContact, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post emergency_contacts_url, params: { emergency_contact: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested emergency_contact" do
        emergency_contact = EmergencyContact.create! valid_attributes
        patch emergency_contact_url(emergency_contact), params: { emergency_contact: new_attributes }
        emergency_contact.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the emergency_contact" do
        emergency_contact = EmergencyContact.create! valid_attributes
        patch emergency_contact_url(emergency_contact), params: { emergency_contact: new_attributes }
        emergency_contact.reload
        expect(response).to redirect_to(emergency_contact_url(emergency_contact))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        emergency_contact = EmergencyContact.create! valid_attributes
        patch emergency_contact_url(emergency_contact), params: { emergency_contact: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested emergency_contact" do
      emergency_contact = EmergencyContact.create! valid_attributes
      expect {
        delete emergency_contact_url(emergency_contact)
      }.to change(EmergencyContact, :count).by(-1)
    end

    it "redirects to the emergency_contacts list" do
      emergency_contact = EmergencyContact.create! valid_attributes
      delete emergency_contact_url(emergency_contact)
      expect(response).to redirect_to(emergency_contacts_url)
    end
  end
end
