require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mission_orders", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MissionOrder. As you add validations to MissionOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MissionOrder.create! valid_attributes
      get mission_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mission_order = MissionOrder.create! valid_attributes
      get mission_order_url(mission_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mission_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mission_order = MissionOrder.create! valid_attributes
      get edit_mission_order_url(mission_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MissionOrder" do
        expect {
          post mission_orders_url, params: { mission_order: valid_attributes }
        }.to change(MissionOrder, :count).by(1)
      end

      it "redirects to the created mission_order" do
        post mission_orders_url, params: { mission_order: valid_attributes }
        expect(response).to redirect_to(mission_order_url(MissionOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MissionOrder" do
        expect {
          post mission_orders_url, params: { mission_order: invalid_attributes }
        }.to change(MissionOrder, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mission_orders_url, params: { mission_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mission_order" do
        mission_order = MissionOrder.create! valid_attributes
        patch mission_order_url(mission_order), params: { mission_order: new_attributes }
        mission_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mission_order" do
        mission_order = MissionOrder.create! valid_attributes
        patch mission_order_url(mission_order), params: { mission_order: new_attributes }
        mission_order.reload
        expect(response).to redirect_to(mission_order_url(mission_order))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mission_order = MissionOrder.create! valid_attributes
        patch mission_order_url(mission_order), params: { mission_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mission_order" do
      mission_order = MissionOrder.create! valid_attributes
      expect {
        delete mission_order_url(mission_order)
      }.to change(MissionOrder, :count).by(-1)
    end

    it "redirects to the mission_orders list" do
      mission_order = MissionOrder.create! valid_attributes
      delete mission_order_url(mission_order)
      expect(response).to redirect_to(mission_orders_url)
    end
  end
end
