require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/time_off_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TimeOffRequest. As you add validations to TimeOffRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TimeOffRequest.create! valid_attributes
      get time_off_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      time_off_request = TimeOffRequest.create! valid_attributes
      get time_off_request_url(time_off_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_time_off_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      time_off_request = TimeOffRequest.create! valid_attributes
      get edit_time_off_request_url(time_off_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TimeOffRequest" do
        expect {
          post time_off_requests_url, params: { time_off_request: valid_attributes }
        }.to change(TimeOffRequest, :count).by(1)
      end

      it "redirects to the created time_off_request" do
        post time_off_requests_url, params: { time_off_request: valid_attributes }
        expect(response).to redirect_to(time_off_request_url(TimeOffRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TimeOffRequest" do
        expect {
          post time_off_requests_url, params: { time_off_request: invalid_attributes }
        }.to change(TimeOffRequest, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post time_off_requests_url, params: { time_off_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested time_off_request" do
        time_off_request = TimeOffRequest.create! valid_attributes
        patch time_off_request_url(time_off_request), params: { time_off_request: new_attributes }
        time_off_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the time_off_request" do
        time_off_request = TimeOffRequest.create! valid_attributes
        patch time_off_request_url(time_off_request), params: { time_off_request: new_attributes }
        time_off_request.reload
        expect(response).to redirect_to(time_off_request_url(time_off_request))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        time_off_request = TimeOffRequest.create! valid_attributes
        patch time_off_request_url(time_off_request), params: { time_off_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested time_off_request" do
      time_off_request = TimeOffRequest.create! valid_attributes
      expect {
        delete time_off_request_url(time_off_request)
      }.to change(TimeOffRequest, :count).by(-1)
    end

    it "redirects to the time_off_requests list" do
      time_off_request = TimeOffRequest.create! valid_attributes
      delete time_off_request_url(time_off_request)
      expect(response).to redirect_to(time_off_requests_url)
    end
  end
end
