name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: start the db
        run: docker-compose up -d db
      - name: Build the stack
        run: docker-compose run web bundle exec rails db:create
      - name: run migrations
        run: docker-compose run web  bundle exec rails db:migrate
      - name: run selenium
        run: docker-compose up -d web selenium
      - name: rspec
        run: docker-compose exec -t web bash -c "bundle exec rspec"
      - name: logfiles
        run: ls -alrt coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
